In [5]:
import numpy as np
import pandas

In [10]:
array = np.array([[1,2,3],[2,3,4]])
print(array)
print(array.ndim)  #維度
print(array.shape) #行數+列數
print(array.size)  #元素數

[[1 2 3]
 [2 3 4]]
2
(2, 3)
6


In [13]:
import numpy as np2
#a = np2.array([1,2,3,4],dtype = np.float)
a = np2.array([1,2,3,4],dtype = np.int)
print(a.dtype)

int64


In [18]:
import numpy as np3
#a = np3.zeros((3,4))  #生成3列4欄，全部為0的陣列
#a = np3.ones((3,4))   #生成3列4欄，全部為1的陣列
#a = np3.arange(10,20,2)  #生成10~20間隔為2的陣列
a = np3.arange(12).reshape((3,4))  #生成0~11,3列4欄的陣列
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
